sudo: false
language: python
python:
  - 3.2
  - 3.4

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  - pip
  - directories:
    - $HOME/.cache/pip

before_install:
  - pip install coveralls

install:
  - python setup.py install

script:
  - python setup.py test --pytest-args '-vv --full-trace'

after_success:
  - coveralls
