sudo: false
language: python
python:
  - 3.2
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly
matrix:
  allow_failures:
    - python: 3.5-dev
    - python: nightly


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  - pip
  - directories:
    - $HOME/.cache/pip

before_install:
  - pip install --upgrade pip setuptools
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
  - pip install coveralls

install:
  - python setup.py install

script:
  - python setup.py test --pytest-args '-vv --full-trace --pep8 --cov=tchart'

after_success:
  - coveralls
