sudo: false
language: python
os:
  - linux
  - osx
python:
  - 3.2
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly
matrix:
  allow_failures:
    - os: osx
    - python: 3.5-dev
    - python: nightly


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  - pip
  - directories:
    - $HOME/.cache/pip

before_install:
  - case ${TRAVIS_PYTHON_VERSION} in
      3.2) pip install --upgrade pip\<8 setuptools wheel coveralls coverage\<4 codacy-coverage git+git://github.com/andras-tim/pytest-pylint
           ;;
      *)   pip install --upgrade pip setuptools wheel coveralls codacy-coverage git+git://github.com/andras-tim/pytest-pylint
           ;;
    esac

install:
  - python setup.py install

script:
  - python setup.py test --pytest-args '-vv --full-trace --cov=tchart'

after_success:
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
